package arda.mybatis.dao;

import arda.mybatis.model.ItemSupplier;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ItemSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM_SUPPLIER
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    int insert(ItemSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM_SUPPLIER
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    List<ItemSupplier> selectAll();
}