package arda.mybatis.dao;

import arda.mybatis.model.Item;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    List<Item> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    int updateByPrimaryKey(Item record);
}