package arda.mybatis.dao;

import arda.mybatis.model.Warehouse;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface WarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WAREHOUSE
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WAREHOUSE
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    int insert(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WAREHOUSE
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    Warehouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WAREHOUSE
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    List<Warehouse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WAREHOUSE
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    int updateByPrimaryKey(Warehouse record);
}