package arda.mybatis.model;

import javax.enterprise.inject.Model;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.ID
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.NAME
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.VERSION
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.WEIGHT
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.WAREHOUSE_ID
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    private Integer warehouseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.ID
     *
     * @return the value of PUBLIC.ITEM.ID
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.ID
     *
     * @param id the value for PUBLIC.ITEM.ID
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.NAME
     *
     * @return the value of PUBLIC.ITEM.NAME
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.NAME
     *
     * @param name the value for PUBLIC.ITEM.NAME
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.VERSION
     *
     * @return the value of PUBLIC.ITEM.VERSION
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.VERSION
     *
     * @param version the value for PUBLIC.ITEM.VERSION
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.WEIGHT
     *
     * @return the value of PUBLIC.ITEM.WEIGHT
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.WEIGHT
     *
     * @param weight the value for PUBLIC.ITEM.WEIGHT
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.WAREHOUSE_ID
     *
     * @return the value of PUBLIC.ITEM.WAREHOUSE_ID
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.WAREHOUSE_ID
     *
     * @param warehouseId the value for PUBLIC.ITEM.WAREHOUSE_ID
     *
     * @mbg.generated Tue Apr 28 15:47:20 EEST 2020
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }
}